<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>

    <ApplicationIcon>icon.ico</ApplicationIcon>

    <AssemblyName>ModifierTool</AssemblyName>
    <Product>ModifierTool</Product>
    <RootNamespace>ModifierTool</RootNamespace>
    <Title>ModifierTool</Title>
  </PropertyGroup>

  <ItemGroup>
    <SplashScreen Include="Assets\splash.png" />
  </ItemGroup>

</Project>